# Generated by Django 4.2 on 2025-06-05 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='paid_on',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='policy_number',
        ),
        migrations.AddField(
            model_name='payment',
            name='policy_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='policy_type',
            field=models.CharField(choices=[('car', 'Car Insurance'), ('health', 'Health Insurance')], default='car', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
