# Generated by Django 4.2 on 2025-06-06 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='filed_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='amount_claimed',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='claim_number',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='policy_number',
        ),
        migrations.AddField(
            model_name='claim',
            name='date_of_incident',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='policy_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='policy_type',
            field=models.CharField(choices=[('car', 'Car Insurance'), ('health', 'Health Insurance')], default='car', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
